### ISSUE TITLE
Sed error when executing xbian-config bootflags update 

### ISSUE THREAD

**Issue by eremem** [xbianonpi/xbian-config-bash#37]
When executing any of the `sudo xbian-config bootflags update` variants, (e.g. `sudo xbian-config bootflags update quiet 1`)
the following error is reported:
`sed: unrecognized option '--startup-event'`

My system is up-to-date.

**Comment by mkreisl** [comment]
Honestly, what do you use this function for? it hasn't been used internally for ages, so the likelihood of it being fixed is very, very low.
Of course you can create a PR to solve this problem.

**Comment by eremem** [comment]
I'm trying to automate the configuration after installing xbian, so that I don't have to do a ton of customization on each of my STBs. Is there an another "xbian-compatible" way to achieve this like it was supported by xbian-config or do I have to change the actual settings on the OS level?

**Comment by mkreisl** [comment]
You will have no other choice.
I was able to find and fix the problem mentioned above, but the function itself is total garbage, it does more damage than good. I won't bother with it any further

**Comment by eremem** [comment]
Thank you for the fix. Apart from that, does it mean that `xbian-config` in regard to its interactive mode should also be considered obsolete? As far as I can tell it also uses the same modules code under the hood, doesn't it?

**Comment by mkreisl** [comment]
The parameter `--startup-event mountall` was added in 2013. I.e. since then the thing no longer works. Which in turn means that no one has used this function since then, whether as a cmdline function or within the console-gui - including me.
And yes, the console xbian-config is practically no longer maintained

**Comment by eremem** [comment]
I see, thank you for clarifying that.
